---
openapi: 3.0.1
info:
  version: "1.0"
  title: Osbuild-installer backend service
  description: Service that relays image build requests
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "/{{.PathPrefix}}/{{.AppName}}/v1"

paths:
  /version:
    get:
      summary: get the service version
      description: "get the service version"
      operationId: osbuild_installer.views.v1.get_version
      responses:
        '200':
          description: a service version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'

components:
  schemas:
    Version:
      required:
        - version
      properties:
        version:
          type: string
